url: https:/imageanalysis.github.io
baseurl: /openaccess/

# Site settings
title: IMAGE ANALYSIS LTD
email: support@imageanalysis.co.uk
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff4719
  secondary: cc3914
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Mark Hinton
  pic: 1
  position: Chief Technical Officer
  social:
    - title: linkedin
      url: uk.linkedin.com/in/markhinton
    - title: envelope
      url: mailto:mark.hinton@imageanalysis.org.uk

- name: Olga Kubassova, Ph.D.
  pic: 2
  position: Founder and Chief Executive Officer
  social:
    - title: twitter
      url: twitter.com/OlgaKubassova
    - title: linkedin
      url: uk.linkedin.com/in/olgakubassova
    - title: envelope
      url: mailto:olga@imageanalysis.org.uk

- name: Diana Roettger, Ph.D.
  pic: 3
  position: Scientific Project Officer
  social:
    - title: linkedin
      url: uk.linkedin.com/in/dianaroettger
    - title: envelope
      url: mailto:diana.roettger@imageanalysis.org.uk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/imageanalysis
  - title: facebook
    url: #


# Postal address (add as many lines as necessary)
address:
  - line: Image Analysis Ltd
  - line: QABC Minster House
  - line: 272-274 Vauxhall Bridge Road
  - line: SW1V 1BA
  - line: London
  - line: United Kingdom

# Build settings
markdown: kramdown
permalink: pretty
